### PR TITLE
Add link to Redis Quick Start doc

### PR DESCRIPTION
**Pull request by itamarhaber**

### CODE REVIEW

**Comment by djanowski** [comment]
Can you make the URL relative?

**Comment by itamarhaber** [comment]
@djanowski giving myself :facepunch:

**Comment by antirez** [comment]
No problem in merging this as soon as we check the quickstart is updated given it will be more relevant. I saw at least a couple of things which are no longer ok...

**Comment by djanowski** [comment]
@antirez Maybe if you list what's not OK @itamarhaber can fix it :)

**Pull request closed without merging**
