### PR TITLE
Great video that explains Redis

### PR DESCRIPTION
**Pull request by knoxcard**
This should be smack dab in the center of the homepage.  It sums up Redis so well and is easy for anyone to understand. 

The video has 49 likes, 0 dislikes.  Only viewed 6,000 times on YouTube.

### CODE REVIEW

**Comment by itamarhaber** [comment]
@knoxcard I couldn't disagree more :)

**Comment by knoxcard** [comment]
You disagree? You do NOT want the video on the homepage? lol.  
Just verifying, feel free to disagree. lol.

**Comment by antirez** [comment]
Hey, we tend to be a bit more vendor neutral, don't really love marketing, and pretend that our users which are developers can capture the same info by reading material instead of watching videos. Hey nothing wrong with watching videos, but later, at night when you are tired... a bit of Netflix can't hurt.

**Comment by itamarhaber** [comment]
Yep, we're in total disagreement but for your amusement I'll provide the background: redis.io is devoted to the open source Redis project, and as such it is focused on developers and is devoid of commercial content. The video, which was produced by Redis Labs (my employer and a commercial company), fails on both counts.

That said, I'm glad that you found it useful :)

**Pull request closed without merging**
